site_name: GPUQ Docs

theme:
  name: material
  logo: assets/gpuq.png
  favicon: assets/gpuq.png
  custom_dir: docs/overrides
  language: es
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand
    - toc.integrate
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2
  - i18n:
      docs_structure: folder
      languages:

        - locale: es
          name: Español
          build: true
          default: true
          nav:
            - Inicio: index.md
            - Introducción:
                - ¿Qué es Docker?: introduccion/que-es-docker.md
                - ¿Qué es gpuq?: introduccion/que-es-gpuq.md

            - Docker:
                - Conceptos básicos: docker/conceptos-basicos.md
                - Crear un Dockerfile: docker/dockerfile.md
                - Usar docker-compose: docker/docker-compose.md

            - Experimentos:
                - Estructura de un experimento: experimentos/estructura-experimento.md
                - Ejecutar contenedores Docker: experimentos/ejecutar-contenedores.md
                - Ejemplo mínimo: experimentos/ejemplo-minimo.md

            - Uso de gpuq:
                - Ejecutar trabajos: gpuq/ejecutar-trabajos.md
                - Monitorizar trabajos: gpuq/monitorizar-trabajos.md
                - Logs y resultados: gpuq/logs-y-resultados.md

        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Introduction:
                - What is Docker?: introduccion/que-es-docker.md
                - What is gpuq?: introduccion/que-es-gpuq.md

            - Docker:
                - Basic concepts: docker/conceptos-basicos.md
                - Creating a Dockerfile: docker/dockerfile.md
                - Using docker-compose: docker/docker-compose.md

            - Experiments:
                - Experiment structure: experimentos/estructura-experimento.md
                - Running Docker containers: experimentos/ejecutar-contenedores.md
                - Minimal example: experimentos/ejemplo-minimo.md

            - Using gpuq:
                - Running jobs: gpuq/ejecutar-trabajos.md
                - Monitoring jobs: gpuq/monitorizar-trabajos.md
                - Logs and results: gpuq/logs-y-resultados.md

site_url: https://enolgargon.github.io/gpuq-docs
repo_url: https://github.com/enolgargon/gpuq
repo_name: enolgargon/gpuq
site_description: Documentación para el uso de Docker y la herramienta GPUQ en la ejecución de experimentación.
site_author: Enol García González

copyright: >
  Documentation licensed under CC BY-SA 4.0